definitions:
  pkg.TaskCreateReq:
    properties:
      detail:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /task:
    get:
      consumes:
      - application/json
      parameters:
      - default: desc
        description: desc/asc default(desc)
        in: query
        name: order
        type: string
      - description: search
        in: query
        name: search
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: List akun
      tags:
      - Akun
    post:
      consumes:
      - application/json
      description: create string by ID
      operationId: create-string-by-int
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pkg.TaskCreateReq'
      produces:
      - application/json
      responses: {}
      summary: Add a new pet to the store
  /task/{id}:
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Detail akun
      tags:
      - Akun
swagger: "2.0"
